#!/bin/bash
# Quick start script for DocStrange Docker deployment

set -e

# Function to show usage
show_usage() {
    echo "Usage: $0 <NANONETS_API_KEY> [mode]"
    echo ""
    echo "Arguments:"
    echo "  NANONETS_API_KEY   Your Nanonets API key (required)"
    echo "  mode               Optional: 'cloud', 'gpu', or 'both' (default: cloud)"
    echo ""
    echo "Examples:"
    echo "  $0 your_api_key_here"
    echo "  $0 your_api_key_here cloud"
    echo "  $0 your_api_key_here gpu"
    echo "  $0 your_api_key_here both"
    echo ""
    echo "Get your API key from: https://app.nanonets.com/#/keys"
    echo "Free tier available at: https://nanonets.com"
    exit 1
}

# Check if API key is provided
if [ -z "$1" ]; then
    echo "❌ Error: NANONETS_API_KEY is required!"
    echo ""
    show_usage
fi

API_KEY="$1"
MODE="${2:-cloud}"  # Default to cloud mode if not specified

echo "🚀 DocStrange Docker Quick Start"
echo "================================"
echo ""

# Check if Docker is installed
if ! command -v docker &> /dev/null; then
    echo "❌ Docker is not installed. Please install Docker first:"
    echo "   https://docs.docker.com/get-docker/"
    exit 1
fi

# Check if Docker Compose is installed
if ! command -v docker-compose &> /dev/null; then
    echo "❌ Docker Compose is not installed. Please install Docker Compose:"
    echo "   https://docs.docker.com/compose/install/"
    exit 1
fi

echo "✅ Docker found: $(docker --version)"
echo "✅ Docker Compose found: $(docker-compose --version)"
echo "✅ API key provided"
echo ""

# Create .env file with API key
echo "📝 Creating .env file with your API key..."
cat > .env << EOF
# DocStrange Environment Configuration
# Generated by docker-start.sh on $(date)

# Nanonets API Key
NANONETS_API_KEY=$API_KEY

# Flask Configuration
FLASK_ENV=production
FLASK_DEBUG=0

# Application Settings
MAX_CONTENT_LENGTH=104857600

# Host and Port
HOST=0.0.0.0
PORT=8000
EOF
echo "✅ Created .env file"
echo ""

# Determine which mode to start based on argument
case $MODE in
    cloud|1)
        echo ""
        echo "🌥️  Starting DocStrange in cloud mode..."
        docker-compose up -d docstrange-cloud
        
        echo ""
        echo "✅ DocStrange is starting up!"
        echo "🌐 Web interface: http://localhost:8000"
        echo "📊 Health check: http://localhost:8000/api/health"
        echo ""
        echo "View logs with: docker-compose logs -f docstrange-cloud"
        echo "Stop with: docker-compose down"
        ;;
    gpu|2)
        # Check for NVIDIA GPU
        echo ""
        if docker run --rm --gpus all nvidia/cuda:11.8.0-base-ubuntu22.04 nvidia-smi &> /dev/null; then
            echo "🎮 GPU detected! Starting DocStrange in GPU mode..."
        else
            echo "⚠️  WARNING: GPU not detected or nvidia-docker not installed"
            echo "Container will start but GPU acceleration may not work."
            echo ""
            echo "To enable GPU support, ensure:"
            echo "  1. You have an NVIDIA GPU"
            echo "  2. NVIDIA drivers are installed"
            echo "  3. nvidia-docker is installed: https://github.com/NVIDIA/nvidia-docker"
            echo ""
            echo "Starting anyway..."
        fi
        
        docker-compose --profile gpu up -d docstrange-gpu
        
        echo ""
        echo "✅ DocStrange is starting up!"
        echo "🌐 Web interface: http://localhost:8001"
        echo "📊 Health check: http://localhost:8001/api/health"
        echo ""
        echo "⚠️  First startup may take 5-10 minutes to download GPU models"
        echo ""
        echo "View logs with: docker-compose logs -f docstrange-gpu"
        echo "Stop with: docker-compose --profile gpu down"
        ;;
    both|3)
        echo ""
        echo "🚀 Starting DocStrange in both modes..."
        docker-compose --profile gpu up -d
        
        echo ""
        echo "✅ DocStrange is starting up!"
        echo "🌐 Cloud mode: http://localhost:8000"
        echo "🌐 GPU mode:   http://localhost:8001"
        echo ""
        echo "View logs with: docker-compose logs -f"
        echo "Stop with: docker-compose --profile gpu down"
        ;;
    *)
        echo "❌ Invalid mode: $MODE"
        echo "Valid modes: cloud, gpu, both"
        show_usage
        ;;
esac

echo ""
echo "📚 For more information, see DOCKER.md"
echo "💡 Use 'make help' to see available commands"
